My Project: Square.cpp File Reference
Square.cpp File Reference
#include <cstdio>
#include <cmath>
#include <cassert>
#include <string.h>
#include "input_output.h"
#include "test.h"
#include "solve_square.h"
#include "consts.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
< коэффициенты квадртатного уравнения
< корни кваратного уравненния
< количество корней уравнения //энам
Definition at line 21 of file Square.cpp.
{
    double a = 0, b = 0, c = 0;
    double x1 = 0, x2 = 0;
    int n_roots = 0;
    for (int i=1; i<argc; i++)
    {
        if (argv[i][1]== 'n') // "./SQE tn"
            {
                if (select_input())
                    input_coeffs_kb (&a, &b, &c);
                else
                    input_coeffs_file (&a, &b, &c);
            n_roots = solve_square (a, b, c, &x1, &x2);
            output_roots (n_roots, x1, x2);
        }
        if (argv[i][1]== 't')
            {
                Test_all();
            }
        if (argv[i][1]== 'h')
            {
                printf ("Аргументы командной строки:\n");
                printf ("1) -h - вызывает описание аргументов командной строки\n");
                printf ("2) -t - включает вывод тестов\n");
                printf ("3) -n - вызывает обычный запуск программы\n");
                return 0;
            }
    }
}
References input_coeffs_file(), input_coeffs_kb(), output_roots(), select_input(), solve_square(), and Test_all().