My Project: input_output.h File Reference
input_output.h File Reference
Functions
void clear_buffer (void)
Функция очистки буфера
void sorting_roots (double *x1, double *x2)
void input_coeffs_file (double *a, double *b, double *c)
Функция ввода коэффициентов через файл
void input_coeffs_kb (double *a, double *b, double *c)
Функция ввода коэффициентов через клавиатуру
bool is_zero (double n)
Сравнивает число типа double с нулем
void output_roots (int n_roots, double x1, double x2)
Функция вывода корней
int select_input (void)
Функция выбора способа ввода коэффициентов
Function Documentation
clear_buffer()
void clear_buffer (void)
Функция очистки буфера
Definition at line 11 of file input_output.cpp.
{
    while (getchar() != '\n');
}
Referenced by input_coeffs_file(), input_coeffs_kb(), and select_input().
input_coeffs_file()
void input_coeffs_file (double * a, double * b, double * c)
Функция ввода коэффициентов через файл
Parameters
[out] a,b,c - адреса переменных коэффициентов квадратного уравнения
Definition at line 67 of file input_output.cpp.
{
   assert (a != NULL);
   assert (b != NULL);
   assert (c != NULL);
   printf ("Введите имя файла\n");
   char name_of_file[90] = {};
   scanf("%s", name_of_file);
   FILE *file = fopen (name_of_file, "r");
   while(fscanf (file, "%lf %lf %lf", a, b, c)!=3)
   {
      printf("Ошибка ввода\n");
      printf ("Введите с клавиатуры\n");
      input_coeffs_kb(a, b, c);
      return;
   }
   fclose(file);
   if (isfinite(*a) && isfinite (*b) && isfinite(*c))
        return;
   else
    {
        printf ("Числа слишком большие\n");
        clear_buffer();
    }
    assert (isfinite(*a));
    assert (isfinite(*b));
    assert (isfinite(*c));
}
References clear_buffer(), and input_coeffs_kb().
Referenced by main().
input_coeffs_kb()
void input_coeffs_kb (double * a, double * b, double * c)
Функция ввода коэффициентов через клавиатуру
Parameters
[out] a,b,c - адреса переменных коэффициентов квадратного уравнения
Definition at line 40 of file input_output.cpp.
{
    assert (a != NULL);
    assert (b != NULL);
    assert (c != NULL);
    printf ("Введите коэффициенты квадратного уравнения \n");
    while (scanf ("%lf %lf %lf", a, b ,c) != 3)
        {
            clear_buffer();
            printf ("Ошибка ввода. Введите коэффициенты еще раз \n");
        }
    if (isfinite(*a) || isfinite (*b) || isfinite(*c))
        return;
    else
        printf ("Числа слишком большие\n");
    assert (isfinite(*a));
    assert (isfinite(*b));
    assert (isfinite(*c));
}
References clear_buffer().
Referenced by input_coeffs_file(), and main().
is_zero()
bool is_zero (double n)
Сравнивает число типа double с нулем
Parameters
[in] n Сравниваемое число
Returns
Возвращает значение типа bool: true - если число является нулем, и false - если число не является нулем
Definition at line 12 of file solve_square.cpp.
{
    if (fabs(n) < EPS)
       return true;
    else
       return false;
}
References EPS.
output_roots()
void output_roots (int n_roots, double x1, double x2)
Функция вывода корней
Parameters
[in] n_roots - Количество корней квадратного уравнения
[in] x1,x2 - Первый и второй корни квадратного уравнения
Definition at line 104 of file input_output.cpp.
{
    switch (n_roots)
    {
        case ZERO: printf("Нет действительных корней \n");
            break;
        case ONE: printf("Корень уравнения - %.2lf \n", x1);
            break;
        case TWO: printf("Корни квадратного уравнения %.2lf и %.2lf \n", x1, x2);
            break;
        case LINEAR: printf ("Уравнение линейное, его корень %.2lf \n", x1);
            break;
        case INF_ROOTS: printf ("У уравнения бесконечное множество корней \n");
            break;
        default: printf ("Error \n");
    }
}
References INF_ROOTS, LINEAR, ONE, TWO, and ZERO.
Referenced by main().
select_input()
int select_input (void)
Функция выбора способа ввода коэффициентов
Returns
Возвращает true, если выбран ввод с клавиатуры. Возвращает false, если выбран ввод через файл
Definition at line 20 of file input_output.cpp.
{
    int k = 0;
    printf("Выберите способ ввода коэффициентов\n"
           "1) ввод с клавиатуры 2) ввод из файла\n");
    while ((scanf ("%d", &k)!=1) || ((k!=1) && (k!=2)))
        {
            printf ("Попробуйте ещё раз\n");
            clear_buffer();
        }
    if (k == 1)
        return true;
    else if (k == 2)
        return false;
}
References clear_buffer().
Referenced by main().
sorting_roots()
void sorting_roots (double * x1, double * x2)