My Project: solve_square.cpp File Reference
solve_square.cpp File Reference
#include <cstdio>
#include <cassert>
#include <cmath>
#include "consts.h"
Functions
bool is_zero (double n)
Сравнивает число типа double с нулем
int solve_linear (double b, double c, double *x1)
Решает линейное уравнение
void sort_roots (double *x1, double *x2)
Сортирует корни по возрастанию
int solve_square (double a, double b, double c, double *x1, double *x2)
Решает квадратное уравнение
Function Documentation
is_zero()
bool is_zero (double n)
Сравнивает число типа double с нулем
Parameters
[in] n Сравниваемое число
Returns
Возвращает значение типа bool: true - если число является нулем, и false - если число не является нулем
Definition at line 12 of file solve_square.cpp.
{
    if (fabs(n) < EPS)
       return true;
    else
       return false;
}
References EPS.
Referenced by solve_linear(), and solve_square().
solve_linear()
int solve_linear (double b, double c, double * x1)
Решает линейное уравнение
Parameters
[in] b,c - коэффициенты линейного уравнения;
[out] x1 - адрес первого корня
Returns
Возвращает количество корней
Definition at line 26 of file solve_square.cpp.
{
    if (is_zero(b))
       return ZERO;
    else
        {
            *x1 = -c/b;
            return LINEAR;
        }
}
References is_zero(), LINEAR, and ZERO.
Referenced by solve_square().
solve_square()
int solve_square (double a, double b, double c, double * x1, double * x2)
Решает квадратное уравнение
Parameters
[in] a,b,c - коэффициенты квадратного уравнения
[out] x1,x2 - адреса первого и второго корней
Returns
Возвращает количество корней
Definition at line 57 of file solve_square.cpp.
{
    assert (isfinite (a));
    assert (isfinite (b));
    assert (isfinite (c));
    assert (x1 != NULL);
    assert (x2 != NULL);
    double tmp = 0;
    double d = b*b - 4*a*c;
    if (is_zero(a) && is_zero(b) && !(is_zero (c)))
        return ZERO;
    else if (is_zero(a) && is_zero(b) && is_zero(c))
        return INF_ROOTS;
    else if (a == 0)
        {
            tmp = solve_linear(b, c, x1);
            return tmp;
        }
    if (is_zero(d))
        {
            *x1 = (-b + sqrt(d))/(2*a);
            return ONE;
        }
    else if (d < 0)
            return ZERO;
    else if (d > 0)
        {
            *x1 = (-b - sqrt(d))/(2*a);
            *x2 = (-b + sqrt(d))/(2*a);
            sort_roots(x1, x2);
            return TWO;
        }
        return 0;
}
References INF_ROOTS, is_zero(), ONE, solve_linear(), sort_roots(), TWO, and ZERO.
Referenced by main(), and Test_one().
sort_roots()
void sort_roots (double * x1, double * x2)
Сортирует корни по возрастанию
Parameters
[out] x1,x2 адреса корней квадратного уравнения
Definition at line 40 of file solve_square.cpp.
{
    double tmp = 0;
    if (*x1 > *x2)
        {
            tmp = *x1;
            *x1 = *x2;
            *x2 = tmp;
        }
}
Referenced by solve_square().