My Project: test.h File Reference
test.h File Reference
Functions
int Test_one (const struct TestData *allData)
Тест, проверяющий правильность вычисляемых корней квадратного уравнения
int Test_all (void)
Считает количество выполненных тестов и печатает их количество
Function Documentation
Test_all()
int Test_all (void)
Считает количество выполненных тестов и печатает их количество
Definition at line 71 of file test.cpp.
{
    int number_ok_tests = 0;
    for (int i = 0; i < N_TESTS; i++)
        number_ok_tests += Test_one (&allData[i]);
    printf ("Удачных тестов: %d из %d \n", number_ok_tests, N_TESTS);
    return 0;
};
References allData, N_TESTS, and Test_one().
Referenced by main().
Test_one()
int Test_one (const struct TestData * coeffs)
Тест, проверяющий правильность вычисляемых корней квадратного уравнения
Parameters
[in] const struct TestData* coeffs - Ссылка на массив структур
Returns
Возвращает 0, если тест не выполнился. Возвращает 1 если тест выполнился
Definition at line 48 of file test.cpp.
{
    double x1 = 0, x2 = 0;
    int n_roots = solve_square (coeffs->a, coeffs->b, coeffs->c, &x1, &x2);
    int n_rootsref = coeffs -> n_rootsref;
    const char* name = coeffs -> name;
    double x1ref = coeffs -> x1ref;
    double x2ref = coeffs -> x2ref;
    if (compare_numbers (x1, x1ref) || compare_numbers(x2, x2ref) || n_roots!=n_rootsref)
        {
            printf ("%s FAILED: x1 = %lf, x2 = %lf, n_roots = %d\n", name, x1, x2, n_roots);
            printf("\t  EXPECTED: x1ref = %lf, x2ref = %lf, n_rootsref = %d \n", x1ref, x2ref, n_rootsref);
            return 0;
        }
    else
        {
            printf ("Test %s ok \n", name);
            return 1;
        }
}
References TestData::a, TestData::b, TestData::c, compare_numbers(), TestData::n_rootsref, TestData::name, solve_square(), TestData::x1ref, and TestData::x2ref.
Referenced by Test_all().