My Project: test.cpp File Reference
test.cpp File Reference
#include <cstdio>
#include <cassert>
#include <cmath>
#include "solve_square.h"
#include "consts.h"
Classes
struct TestData
Структура, используемая для хранения информации, связанных с тестами
Functions
bool compare_numbers (double n1, double n2)
Сравнивает два числа типа double.
int Test_one (const struct TestData *coeffs)
Тест, проверяющий правильность вычисляемых корней квадратного уравнения
int Test_all (void)
Считает количество выполненных тестов и печатает их количество
Variables
struct TestData allData [N_TESTS]
Структура, используемая для хранения ожидаемых решений квадратного уравнения
Function Documentation
compare_numbers()
bool compare_numbers (double n1, double n2)
Сравнивает два числа типа double.
Parameters
[in] n1,n2 - сравниваемые числа
Returns
Возвращает значние false, если числа равны или true, если они не равны
Definition at line 13 of file test.cpp.
{
    if (fabs (n1-n2) < EPS)
        return false;
    else
        return true;
};
References EPS.
Referenced by Test_one().
Test_all()
int Test_all (void)
Считает количество выполненных тестов и печатает их количество
Definition at line 71 of file test.cpp.
{
    int number_ok_tests = 0;
    for (int i = 0; i < N_TESTS; i++)
        number_ok_tests += Test_one (&allData[i]);
    printf ("Удачных тестов: %d из %d \n", number_ok_tests, N_TESTS);
    return 0;
};
References allData, N_TESTS, and Test_one().
Referenced by main().
Test_one()
int Test_one (const struct TestData * coeffs)
Тест, проверяющий правильность вычисляемых корней квадратного уравнения
Parameters
[in] const struct TestData* coeffs - Ссылка на массив структур
Returns
Возвращает 0, если тест не выполнился. Возвращает 1 если тест выполнился
Definition at line 48 of file test.cpp.
{
    double x1 = 0, x2 = 0;
    int n_roots = solve_square (coeffs->a, coeffs->b, coeffs->c, &x1, &x2);
    int n_rootsref = coeffs -> n_rootsref;
    const char* name = coeffs -> name;
    double x1ref = coeffs -> x1ref;
    double x2ref = coeffs -> x2ref;
    if (compare_numbers (x1, x1ref) || compare_numbers(x2, x2ref) || n_roots!=n_rootsref)
        {
            printf ("%s FAILED: x1 = %lf, x2 = %lf, n_roots = %d\n", name, x1, x2, n_roots);
            printf("\t  EXPECTED: x1ref = %lf, x2ref = %lf, n_rootsref = %d \n", x1ref, x2ref, n_rootsref);
            return 0;
        }
    else
        {
            printf ("Test %s ok \n", name);
            return 1;
        }
}
References TestData::a, TestData::b, TestData::c, compare_numbers(), TestData::n_rootsref, TestData::name, solve_square(), TestData::x1ref, and TestData::x2ref.
Referenced by Test_all().
Variable Documentation
allData
struct TestData allData[N_TESTS]
Initial value:
=
{
    {.a = 0, .b = 0,  .c = 0,  .x1ref = 0,      .x2ref = 0, .n_rootsref = INF_ROOTS, .name = "Inf_Test"},
    {.a = 1, .b = 0,  .c = -4, .x1ref =  -2,    .x2ref = 2, .n_rootsref = TWO,       .name = "B_zero_Test"},
    {.a = 0, .b = 4,  .c = 5,  .x1ref  = -1.25, .x2ref = 0, .n_rootsref = LINEAR,    .name = "Linear_Test"},
    {.a = 4, .b = -9, .c = -9, .x1ref = -0.75,  .x2ref = 3, .n_rootsref = TWO,       .name = "Normal_Test"},
    {.a = 0, .b = 0,  .c = 0,  .x1ref = 0,      .x2ref = 0, .n_rootsref = INF_ROOTS, .name = "Zero_Test"},
}
Структура, используемая для хранения ожидаемых решений квадратного уравнения
Definition at line 34 of file test.cpp.
Referenced by Test_all().